# Generated by Django 2.1.1 on 2018-12-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='images',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='file_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='file_name', max_length=100),
        ),
    ]
